name: Update Markdown Documentation

on:
  push:
    branches: [ main, dev]  
  pull_request:
    branches: [ main, dev]

permissions:
  contents: write  # Required to push changes back to the repository
  pull-requests: write  # Required to create pull requests if needed

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Run markdown-autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.7
        with:
          commit_author: "GitHub Actions <actions@github.com>"
          commit_user_email: "actions@github.com"
          commit_message: "docs: Auto-update documentation"
          output_file_paths: '[../README.md]'  
          categories: '[code-block]'
